# Generated by Django 5.0.2 on 2024-02-27 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_carrer_level_alter_carrer_short_name'),
        ('exam', '0002_alter_stage_stage'),
        ('library', '0004_alter_module_name_alter_question_question_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='aplication_date',
        ),
        migrations.AddField(
            model_name='stage',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de aplicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.IntegerField(max_length=2, verbose_name='Etapa'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Calificación')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.carrer', verbose_name='Carrera')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.stage', verbose_name='Etapa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExamModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('score', models.FloatField(default=0.0, verbose_name='Calificacion')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Examen')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.module', verbose_name='Modulo')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='modules',
            field=models.ManyToManyField(through='exam.ExamModule', to='library.module', verbose_name='Modulos'),
        ),
    ]
