# Generated by Django 5.0.2 on 2024-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_options_exam_created_exam_question_and_more'),
        ('library', '0004_alter_module_name_alter_question_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='correct',
            field=models.CharField(default='-', max_length=5, verbose_name='Correcta'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.ManyToManyField(to='library.question', verbose_name='preguntas'),
        ),
    ]
