# Generated by Django 5.0.2 on 2024-02-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='level',
            field=models.CharField(choices=[('ing', 'Ingenieria'), ('TSU', 'Tecnico Superior Universitario'), ('M', 'Maestria')], max_length=10, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Abreviaturas'),
        ),
    ]
